"""
Block Pydantic Schemas

These schemas define the data validation and serialization for Block (time block) objects.
Blocks represent Pomodoro sessions or time containers that hold tasks.

Schema Types:
- BlockBase: Common fields shared across all schemas
- BlockCreate: Fields required when creating a new block (POST)
- BlockUpdate: Fields that can be updated (PUT/PATCH) - all optional
- Block: Complete block as returned from the API (GET) - includes id and timestamps
"""

from pydantic import BaseModel, Field, field_validator
from datetime import datetime
from typing import Optional


# Base schema with common fields
class BlockBase(BaseModel):
    """
    Base schema for blocks.
    
    A block is a container for organizing and grouping tasks.
    
    Fields:
    - title: Descriptive title for the block (e.g., "Morning Deep Work", "Evening Study")
    - description: Optional description of the block (max 200 characters)
    - block_number: Optional order within a day (e.g., 1, 2, 3 for 1st, 2nd, 3rd block)
    - day_number: Optional day number in the schedule (1-5)
    - category_id: Optional category/project for this block (all tasks inherit this)
    """
    title: str = Field(..., min_length=1, max_length=200, description="Block title")
    description: Optional[str] = Field(None, max_length=200, description="Block description")
    block_number: Optional[int] = Field(None, ge=1, description="Order within the day (1, 2, 3, ...)")
    day_number: Optional[int] = Field(None, ge=1, le=5, description="Day of cycle (1-5)")
    category_id: Optional[str] = Field(None, description="ID of the category/project for this block")


# Schema for creating a new block (POST request)
class BlockCreate(BlockBase):
    """
    Schema for creating a new block.
    Inherits all fields from BlockBase.
    
    No id or created_at needed - these are auto-generated by the database.
    
    Example:
    {
        "title": "Morning Deep Work",
        "description": "Focus on coding projects",
        "block_number": 1,
        "day_number": 1
    }
    """
    pass


# Schema for updating an existing block (PUT/PATCH request)
class BlockUpdate(BaseModel):
    """
    Schema for updating a block.
    All fields are optional - only provide fields you want to update.
    
    Example (partial update):
    {
        "title": "Updated Block Title",
        "description": "New description",
        "block_number": 2
    }
    """
    title: Optional[str] = Field(None, min_length=1, max_length=200)
    description: Optional[str] = Field(None, max_length=200)
    block_number: Optional[int] = Field(None, ge=1)
    day_number: Optional[int] = Field(None, ge=1, le=5)


# Schema for block as stored in database and returned by API (GET response)
class Block(BlockBase):
    """
    Complete block schema as returned by the API.
    Includes all fields from BlockBase plus database-generated fields.
    
    Additional fields:
    - id: UUID string identifier
    - created_at: When the block was created
    
    Example response:
    {
        "id": "123e4567-e89b-12d3-a456-426614174000",
        "title": "Morning Deep Work",
        "description": "Focus on coding projects",
        "block_number": 1,
        "day_number": 1,
        "created_at": "2024-01-15T10:30:00"
    }
    """
    id: str
    created_at: datetime
    
    class Config:
        """
        Pydantic configuration:
        - from_attributes: Allows creation from SQLAlchemy models (ORM mode)
        This enables: Block.model_validate(db_block_object)
        """
        from_attributes = True

